# Generated by Django 4.2.7 on 2023-11-09 05:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasharaapp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='products',
            name='origin',
            field=models.CharField(default='kenya', max_length=50),
        ),
    ]
